apiVersion: extensions/v1beta1
kind: Deployment
metadata:
    name: alfresco-adf-demo
    annotations:
        deployment.kubernetes.io/revision: "1"
    generation: 1
    labels:
        app: alfresco-adf-demo
spec:
    progressDeadlineSeconds: 600
    replicas: 1
    revisionHistoryLimit: 10
    selector:
        matchLabels:
            run: alfresco-adf-demo
    strategy:
        rollingUpdate:
            maxSurge: 1
            maxUnavailable: 1
        type: RollingUpdate
    template:
        metadata:
            creationTimestamp: null
            labels:
                run: alfresco-adf-demo
        spec:
            containers:
                - image: sphereonregistrydev.azurecr.io/alfresco/adf-demo:latest
                  imagePullPolicy: Always
                  name: alfresco-adf-demo
                  ports:
                      - containerPort: 4200
                        protocol: TCP
                  resources: {}
                  terminationMessagePath: /dev/termination-log
                  terminationMessagePolicy: File
                  volumeMounts:
                      - mountPath: /usr/share/nginx/html/app.config.json
                        name: triall-app-config
                        subPath: app.config.json
            dnsPolicy: ClusterFirst
            imagePullSecrets:
                - name: sphereonregistrydev
            restartPolicy: Always
            schedulerName: default-scheduler
            securityContext: {}
            terminationGracePeriodSeconds: 30
            volumes:
                - configMap:
                      defaultMode: 420
                      name: triall-app-config
                  name: triall-app-config
