apiVersion: extensions/v1beta1
kind: Ingress
metadata:
    name: alfresco-factom-demo
    namespace: triall
    annotations:
        kubernetes.io/ingress.class: "nginx"
        # Default limit is 1m, document(s) above this size will throw 413 (Request Entity Too Large) error
        nginx.ingress.kubernetes.io/proxy-body-size: 5g
        nginx.ingress.kubernetes.io/base-url-scheme: "https"
        nginx.ingress.kubernetes.io/add-base-url: "true"
        nginx.ingress.kubernetes.io/rewrite-target: /
        nginx.ingress.kubernetes.io/configuration-snippet: |
            location ~ ^(/.*/proxy/alfresco/api/solr/.*)$ {return 403 ;}
                        location ~ ^(/.*/-default-/proxy/alfresco/api/.*)$ {return 403;}

spec:
    rules:
    - http:
          paths:
          - path: /factom-demo
            backend:
                serviceName: alfresco-factom-demo
                servicePort: 80
